development:
  adapter: postgresql
  database: kratos_dev
  pool: 5
  timeout: 5000
  username:
  password:

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kratos
  pool: 5
  timeout: 5000
  username:
  password:

cucumber:
  <<: *test
